"""Dataset validation pipeline for DysLexAI Phase 1."""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

from src.reading_model.data_loader import ReadingDataLoader
from src.typing_model.data_loader import TypingDataLoader
from src.utils.config import CONFIG, DatasetConfig
from src.utils.file_utils import hash_file, is_empty_file, list_files, write_text
from src.utils.logger import get_logger
from src.writing_model.data_loader import WritingDataLoader

LOGGER = get_logger(__name__)


@dataclass
class ValidationIssue:
    """One validation warning or error."""

    severity: str
    dataset: str
    check: str
    message: str


@dataclass
class DatasetValidationResult:
    """Validation output for one dataset."""

    dataset_name: str
    dataset_key: str
    files_found: int = 0
    supported_files_found: int = 0
    empty_files: int = 0
    duplicate_files: int = 0
    incorrect_extensions: int = 0
    duplicate_records: Optional[int] = None
    missing_labels: Optional[int] = None
    null_values: Optional[int] = None
    class_distribution: Dict[str, int] = field(default_factory=dict)
    issues: List[ValidationIssue] = field(default_factory=list)


class DatasetValidator:
    """Validate all configured DysLexAI datasets."""

    def __init__(self) -> None:
        """Initialize validation state."""

        self.dataset_configs = CONFIG.dataset_configs()

    def validate_all(self) -> Dict[str, DatasetValidationResult]:
        """Run validation for reading, writing, and typing datasets."""

        results: Dict[str, DatasetValidationResult] = {}
        for key, dataset_config in self.dataset_configs.items():
            result = self._validate_common_files(dataset_config)
            if key == "reading":
                self._validate_tabular(result, ReadingDataLoader().load(), dataset_config)
            elif key == "typing":
                self._validate_tabular(result, TypingDataLoader().load(), dataset_config)
                self._validate_typing_ranges(result, TypingDataLoader().load())
            elif key == "writing":
                self._validate_writing(result)
            results[key] = result
        return results

    def save_report(self, results: Dict[str, DatasetValidationResult]) -> Path:
        """Save a markdown validation report."""

        report_path = CONFIG.reports_dir / "validation_report.md"
        lines = [
            "# DysLexAI Dataset Validation Report",
            "",
            "This report is generated by the Phase 1 validation pipeline.",
            "",
        ]
        for result in results.values():
            lines.extend(self._format_dataset_result(result))
        write_text(report_path, "\n".join(lines) + "\n")
        LOGGER.info("Validation report saved to %s", report_path)
        return report_path

    def _validate_common_files(
        self, dataset_config: DatasetConfig
    ) -> DatasetValidationResult:
        """Run file-level checks shared across modalities."""

        result = DatasetValidationResult(
            dataset_name=dataset_config.name,
            dataset_key=dataset_config.key,
        )
        files = list_files(dataset_config.path)
        result.files_found = len(files)
        expected = {extension.lower() for extension in dataset_config.expected_extensions}
        result.supported_files_found = sum(
            1 for path in files if path.suffix.lower() in expected
        )
        result.incorrect_extensions = result.files_found - result.supported_files_found

        # Missing directories and empty folders are warnings, not hard failures.
        if not dataset_config.path.exists():
            result.issues.append(
                ValidationIssue(
                    "warning",
                    dataset_config.key,
                    "missing_files",
                    f"Dataset directory does not exist: {dataset_config.path}",
                )
            )
        elif not files:
            result.issues.append(
                ValidationIssue(
                    "warning",
                    dataset_config.key,
                    "missing_files",
                    "No dataset files were found in the expected directory.",
                )
            )

        hash_counts: Counter[str] = Counter()
        for path in files:
            if path.suffix.lower() not in expected:
                result.issues.append(
                    ValidationIssue(
                        "warning",
                        dataset_config.key,
                        "incorrect_file_extension",
                        f"Unexpected file extension for {path.name}.",
                    )
                )
            if is_empty_file(path):
                result.empty_files += 1
                result.issues.append(
                    ValidationIssue(
                        "warning",
                        dataset_config.key,
                        "empty_file",
                        f"Empty file detected: {path.name}.",
                    )
                )
            else:
                # Content hashes catch renamed duplicate files.
                hash_counts[hash_file(path)] += 1

        result.duplicate_files = sum(count - 1 for count in hash_counts.values() if count > 1)
        if result.duplicate_files:
            result.issues.append(
                ValidationIssue(
                    "warning",
                    dataset_config.key,
                    "duplicate_files",
                    f"{result.duplicate_files} duplicate file(s) detected by content hash.",
                )
            )
        return result

    def _validate_tabular(
        self,
        result: DatasetValidationResult,
        frame: pd.DataFrame,
        dataset_config: DatasetConfig,
    ) -> None:
        """Validate duplicate rows, labels, nulls, imbalance, and ranges."""

        if frame.empty:
            result.issues.append(
                ValidationIssue(
                    "warning",
                    dataset_config.key,
                    "missing_records",
                    "No readable tabular records were loaded.",
                )
            )
            return

        if len(frame) <= 1_000_000:
            result.duplicate_records = int(frame.duplicated().sum())
        else:
            result.duplicate_records = None
            result.issues.append(
                ValidationIssue(
                    "warning",
                    dataset_config.key,
                    "duplicate_records",
                    "Exact duplicate-row validation was skipped because the table exceeds 1,000,000 rows.",
                )
            )
        result.null_values = int(frame.isna().sum().sum())
        if result.duplicate_records:
            result.issues.append(
                ValidationIssue(
                    "warning",
                    dataset_config.key,
                    "duplicate_records",
                    f"{result.duplicate_records} duplicate row(s) detected.",
                )
            )
        if result.null_values:
            result.issues.append(
                ValidationIssue(
                    "warning",
                    dataset_config.key,
                    "null_values",
                    f"{result.null_values} null value(s) detected across tabular fields.",
                )
            )

        label_column = self._find_label_column(frame, dataset_config.label_candidates)
        if label_column is None:
            result.missing_labels = len(frame)
            result.issues.append(
                ValidationIssue(
                    "warning",
                    dataset_config.key,
                    "missing_labels",
                    "No label column was detected.",
                )
            )
        else:
            result.missing_labels = int(frame[label_column].isna().sum())
            result.class_distribution = {
                str(label): int(count)
                for label, count in frame[label_column].value_counts(dropna=True).items()
            }
            self._check_class_imbalance(result, dataset_config.key)

        self._validate_numeric_ranges(result, frame)

    def _validate_writing(self, result: DatasetValidationResult) -> None:
        """Validate handwriting image readability and class folders."""

        records = WritingDataLoader().load_metadata()
        archive_files = [
            path
            for path in list_files(CONFIG.dataset_configs()["writing"].path)
            if path.suffix.lower() in {".zip", ".rar"}
        ]
        if not records:
            if archive_files:
                result.issues.append(
                    ValidationIssue(
                        "warning",
                        "writing",
                        "archive_extraction_required",
                        "Handwriting archives were found, but no extracted image files were readable.",
                    )
                )
            result.issues.append(
                ValidationIssue(
                    "warning",
                    "writing",
                    "missing_images",
                    "No readable handwriting image files were found.",
                )
            )
            return

        label_counts: Dict[str, int] = defaultdict(int)
        for record in records:
            if record.is_corrupted:
                result.issues.append(
                    ValidationIssue(
                        "warning",
                        "writing",
                        "corrupted_files",
                        f"Corrupted image detected: {record.path.name}.",
                    )
                )
            if record.label is None:
                result.missing_labels = (result.missing_labels or 0) + 1
            else:
                label_counts[record.label] += 1
        result.class_distribution = dict(label_counts)
        self._check_class_imbalance(result, "writing")

    def _validate_typing_ranges(
        self, result: DatasetValidationResult, frame: pd.DataFrame
    ) -> None:
        """Run typing-specific timestamp consistency checks."""

        if frame.empty:
            return
        timestamp_columns = [
            column
            for column in frame.columns
            if "time" in column.lower() or "timestamp" in column.lower()
        ]
        for column in timestamp_columns:
            series = pd.to_numeric(frame[column], errors="coerce")
            if series.notna().sum() > 1 and (series.diff().dropna() < 0).any():
                result.issues.append(
                    ValidationIssue(
                        "warning",
                        "typing",
                        "timestamp_consistency",
                        f"Timestamp column {column} contains decreasing values.",
                    )
                )

    def _validate_numeric_ranges(
        self, result: DatasetValidationResult, frame: pd.DataFrame
    ) -> None:
        """Flag common invalid numeric values such as negative durations."""

        numeric_frame = frame.select_dtypes(include="number")
        for column in numeric_frame.columns:
            lower_name = column.lower()
            if any(token in lower_name for token in ["duration", "pause", "latency"]):
                if (numeric_frame[column].dropna() < 0).any():
                    result.issues.append(
                        ValidationIssue(
                            "warning",
                            result.dataset_key,
                            "invalid_feature_ranges",
                            f"Column {column} contains negative values.",
                        )
                    )

    def _check_class_imbalance(
        self, result: DatasetValidationResult, dataset_key: str
    ) -> None:
        """Flag class imbalance when the minority class is under 20 percent."""

        counts = list(result.class_distribution.values())
        if len(counts) < 2:
            return
        total = sum(counts)
        minority_ratio = min(counts) / total if total else 0.0
        if minority_ratio < 0.20:
            result.issues.append(
                ValidationIssue(
                    "warning",
                    dataset_key,
                    "class_imbalance",
                    f"Minority class ratio is {minority_ratio:.2%}.",
                )
            )

    @staticmethod
    def _find_label_column(
        frame: pd.DataFrame, label_candidates: List[str]
    ) -> Optional[str]:
        """Return the first likely label column."""

        lower_to_column = {column.lower(): column for column in frame.columns}
        for candidate in label_candidates:
            if candidate in lower_to_column:
                return lower_to_column[candidate]
        return None

    @staticmethod
    def _format_dataset_result(result: DatasetValidationResult) -> List[str]:
        """Format one dataset result as markdown."""

        lines = [
            f"## {result.dataset_name}",
            "",
            "| Metric | Value |",
            "| --- | ---: |",
            f"| Files found | {result.files_found} |",
            f"| Supported files | {result.supported_files_found} |",
            f"| Empty files | {result.empty_files} |",
            f"| Incorrect extensions | {result.incorrect_extensions} |",
            f"| Duplicate files | {result.duplicate_files} |",
            f"| Duplicate records | {result.duplicate_records if result.duplicate_records is not None else 'N/A'} |",
            f"| Missing labels | {result.missing_labels if result.missing_labels is not None else 'N/A'} |",
            f"| Null values | {result.null_values if result.null_values is not None else 'N/A'} |",
            "",
            "### Class Distribution",
            "",
        ]
        if result.class_distribution:
            lines.extend(["| Class | Count |", "| --- | ---: |"])
            lines.extend(
                f"| {label} | {count} |"
                for label, count in result.class_distribution.items()
            )
        else:
            lines.append("No class distribution could be computed.")

        lines.extend(["", "### Warnings", ""])
        if result.issues:
            lines.extend(
                f"- **{issue.check}**: {issue.message}" for issue in result.issues
            )
        else:
            lines.append("- No validation warnings were detected.")
        lines.append("")
        return lines
